name: 自动化部署

on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux
    steps:
      - name: 拉取代码
        uses: https://gitee.com/lzhuii/checkout@v4
      - name: 清理 Hugo 文章目录
        run: rm -rf /usr/local/nginx/html/blog/*
      - name: 静态化网站
        run: hugo          
      - name: 提取字体
        run: |
          find public -type f -name "*[html,css,js,json,txt]" | xargs cat >> tmp.txt
          fonttools subset "/usr/share/fonts/LXGWWenKai-Regular.ttf" --text-file="tmp.txt" --output-file="public/fonts/LXGWWenKai-Regular.ttf" 
      - name: 复制新的文章到 Hugo 目录下
        run: cp -r public/* /usr/local/nginx/html/blog