name: 自动化部署

on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 清理 Hugo 文章目录
        run: rm -rf /opt/nginx/html/blog/content/*
      - name: 复制新的文章到 Hugo 目录下
        run: cp -r posts /opt/nginx/html/blog/content
      - name: 生成字体文件
        run: |
          find /opt/nginx/html/blog -type f -name "*.md" -or -name "*.css" -or -name "*.js" -or -name "*.yaml" -or -name "*.toml" | xargs cat >> tmp.txt
          fonttools subset "/opt/nginx/html/blog/static/fonts/LXGWWenKai-Regular.ttf" --text-file="tmp.txt" --output-file="/opt/nginx/html/blog/static/fonts/LXGWWenKai.ttf"
      - name: 静态化网站
        run: cd /opt/nginx/html/blog && hugo -F --cleanDestinationDir