name: 自动化部署

on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 清理 Hugo 文章目录
        run: rm -rf /opt/nginx/html/blog/content/*
      - name: 复制新的文章到 Hugo 目录下
        run: cp -r posts /opt/nginx/html/blog/content
      - name: 静态化网站
        run: cd /opt/nginx/html/blog && hugo -F --cleanDestinationDir