name: 自动化部署

on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux
    steps:
      - name: 拉取代码
        uses: https://gitee.com/lzhuii/checkout@v4
      - name: 清理 Hugo 文章目录
        run: rm -rf /usr/local/nginx/html/blog/content/posts/*
      - name: 复制新的文章到 Hugo 目录下
        run: cp -r *md /usr/local/nginx/html/blog/content/posts
      - name: 静态化网站
        run: |
          cd /usr/local/nginx/html/blog
          hugo
      - name: 提取字体
        run: |
          find /usr/local/nginx/html/blog/public -type f -name "*[html,css,js,json,txt]" | xargs cat >> tmp.txt
          fonttools subset "/usr/share/fonts/LXGWWenKai-Regular.ttf" --text-file="tmp.txt" --output-file="/usr/local/nginx/html/blog/public/fonts/LXGWWenKai-Regular.ttf"
