name: 自动化部署

on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux
    steps:
      - name: 拉取代码
        uses: https://gitee.com/lzhuii/checkout@v4
      - name: 清理 Hugo 文章目录
        run: rm -rf /usr/local/nginx/html/blog/content/*
      - name: 复制新的文章到 Hugo 目录下
        run: |
          cp -r posts /usr/local/nginx/html/blog/content
          cp -r *md /usr/local/nginx/html/blog/content
      - name: 静态化网站
        run: |
          cd /usr/local/nginx/html/blog
          /usr/local/bin/hugo