name: 自动化部署

on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux
    steps:
      - name: 拉取代码
        uses: https://gitee.com/lzhuii/checkout@v4
      - name: 静态化网站
        run: hugo --baseURL="https://lzhui.top/"
      - name: 清理 Hugo 文章目录
        run: rm -rf /usr/local/nginx/html/blog/*
      - name: 复制新的文章到 Hugo 目录下
        run: cp -r public/* /usr/local/nginx/html/blog